const translations = {
  en: {
    contactBtn: "Contact",
    techTitle: "Technical Stack",
    projectTitle: "Project Documentation",
    contactHero: "Let's discuss your next project",
    backBtn: "Return to Home",
    techSheet: "Technical Specifications",
    mainRole: "Core Responsibility",
    viewProject: "Launch Project",
    location: "Belgium",
    bio: "Game Programmer specializing in scalable systems and high-performance gameplay architecture. I focus on transforming complex logic into optimized, fluid experiences.",
    aboutTitle: "Profile",
    aboutRole: "Systems Engineer & Gameplay Architect",
    aboutText:
      "I believe that well-structured code should be as fluid as the gameplay it sustains. My approach is systemic: I seek to understand the project in its entirety to create solutions that facilitate scalability and maintenance. I am obsessed with event-based systems and organic behaviors, ensuring that every line of code contributes to immersion and high-performance architecture.",
    downloadCV: "Download Resume",
    videoLabel: "Technical Showcase",
    discordLabel: "Discord",
    levelInter: "🔵 Intermediate",
    levelInterBlue: "🔷 Intermediate",
    levelInterGreen: "🟢 Intermediate",
    levelStrong: "🟡 Advanced Intermediate",
    levelWorld: "🌍 Intermediate",
    copySuccess: "Copied!",
  },
  pt: {
    contactBtn: "Contato",
    techTitle: "Stack Técnica",
    projectTitle: "Portfólio de Projetos",
    contactHero: "Vamos viabilizar seu próximo projeto?",
    backBtn: "Voltar ao Início",
    techSheet: "Especificações Técnicas",
    mainRole: "Responsabilidade Principal",
    viewProject: "Ver Projeto",
    location: "Bélgica",
    bio: "Programador de Jogos especializado em sistemas escaláveis e arquitetura de gameplay de alta performance. Foco em transformar lógica complexa em experiências otimizadas e fluidas.",
    aboutTitle: "Perfil",
    aboutRole: "Systems Engineer & Gameplay Architect",
    downloadCV: "Baixar Currículo",
    aboutText:
      "Acredito que um código bem estruturado deve ser tão fluido quanto o gameplay que ele sustenta. Minha abordagem é sistêmica: busco compreender o projeto em sua totalidade para criar soluções que facilitem a escalabilidade e a manutenção. Sou obcecado por sistemas baseados em eventos e comportamentos orgânicos